# Generated by Django 6.1 on 2026-08-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='brands/'),
        ),
    ]
