# Generated by Django 6.1 on 2026-08-16 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_brand_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='products/media/%Y/%m/%d/')),
                ('media_type', models.CharField(choices=[('image', 'تصویر'), ('video', 'ویدیو')], default='image', max_length=10)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='shop.product')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
