# Generated by Django 6.1 on 2026-08-20 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_liked_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liked_items',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='shop.product'),
        ),
    ]
