# Generated by Django 6.1 on 2026-08-30 10:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_product_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Liked_items',
            new_name='LikedItems',
        ),
    ]
